/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yngMain;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author brixd
 */
public class account extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst,pst1;
    ResultSet rs,rs1;
    
    public ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));
    public String empId;
    
    static final String USERNAME = "root";
    static final String PASSWORD = "";
    static final String DATACONN = "jdbc:mysql://localhost/sql12655413";
    
    public account() {
        initComponents();
        setTitle("Grading System");
        setResizable(false);
        super.requestFocus();
        conn = (com.mysql.jdbc.Connection) con();
        setIconImage(logo.getImage()); 
        
    }
    
    public void ac(){
        try{
            pst = conn.prepareStatement("select * from registrar where regId = ?");
            pst.setString(1,id.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                fn.setText(rs.getString("regFn"));
                mn.setText(rs.getString("regMn"));
                ln.setText(rs.getString("regLn"));
                sf.setText(rs.getString("regSf"));
                bd.setDate(rs.getDate("regBdate"));
                cn.setText(rs.getString("regNumber"));
                ad.setText(rs.getString("regAddress"));
                em.setText(rs.getString("regEmail"));
                un.setText(rs.getString("regUn"));
                pw.setText(rs.getString("regPw"));
                pw1.setText(rs.getString("regPw"));
                po.setText(rs.getString("position"));
            }else{
                System.out.println("failed");
            }
            
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null,e);  
        }
    }
    public void ca(){
        try{
            pst = conn.prepareStatement("select * from employee where employeeId = ?");
            pst.setString(1,id.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                fn.setText(rs.getString("efirstName"));
                mn.setText(rs.getString("emiddleName"));
                ln.setText(rs.getString("elastName"));
                sf.setText(rs.getString("eSuffix"));
                bd.setDate(rs.getDate("ebirthDate"));
                cn.setText(rs.getString("eNumber"));
                ad.setText(rs.getString("eAddress"));
                em.setText(rs.getString("eEmail"));
                un.setText(rs.getString("eUsername"));
                pw.setText(rs.getString("ePassword"));
                pw1.setText(rs.getString("ePassword"));
                po.setText(rs.getString("ePosition"));
            }else{
                System.out.println("failed");
            }
            
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null,e);  
        }
    }
    
    public final Connection con(){
        try{
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(DATACONN,USERNAME,PASSWORD);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sf = new javax.swing.JTextField();
        bd = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        po = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Box4 = new javax.swing.JCheckBox();
        Box2 = new javax.swing.JCheckBox();
        pw1 = new javax.swing.JPasswordField();
        pw = new javax.swing.JPasswordField();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account");
        setMinimumSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 330, 40);

        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 150, 16);
        jPanel1.add(fn);
        fn.setBounds(10, 70, 150, 22);

        jLabel3.setText("Middle Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 50, 150, 16);
        jPanel1.add(mn);
        mn.setBounds(180, 70, 150, 22);

        jLabel4.setText("Birth Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 150, 16);
        jPanel1.add(ln);
        ln.setBounds(10, 120, 150, 22);
        jPanel1.add(id);
        id.setBounds(10, 10, 120, 20);

        jLabel5.setText("Suffix");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 100, 150, 16);
        jPanel1.add(sf);
        sf.setBounds(180, 120, 150, 22);

        bd.setDateFormatString("MM-dd-yyyy");
        jPanel1.add(bd);
        bd.setBounds(10, 170, 150, 22);

        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 150, 16);
        jPanel1.add(ad);
        ad.setBounds(10, 230, 320, 22);

        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 210, 320, 16);
        jPanel1.add(cn);
        cn.setBounds(180, 170, 150, 22);

        jLabel8.setText("Contact Number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 150, 150, 16);

        jLabel9.setText("Username");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 310, 150, 16);
        jPanel1.add(un);
        un.setBounds(10, 330, 150, 22);

        jLabel10.setText("Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 360, 150, 16);

        jLabel11.setText("Email");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 260, 150, 16);
        jPanel1.add(em);
        em.setBounds(10, 280, 150, 22);

        jLabel12.setText("Position");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(180, 260, 150, 16);

        po.setEditable(false);
        jPanel1.add(po);
        po.setBounds(180, 280, 150, 22);

        jLabel13.setText("Confirm Password");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 410, 150, 16);

        Box4.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4ActionPerformed(evt);
            }
        });
        jPanel1.add(Box4);
        Box4.setBounds(140, 380, 30, 20);

        Box2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2ActionPerformed(evt);
            }
        });
        jPanel1.add(Box2);
        Box2.setBounds(140, 430, 30, 20);
        jPanel1.add(pw1);
        pw1.setBounds(10, 430, 150, 22);
        jPanel1.add(pw);
        pw.setBounds(10, 380, 150, 22);

        btn.setText("Save");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(btn);
        btn.setBounds(180, 430, 150, 23);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        if(Box2.isSelected()){
            pw1.setEchoChar((char)0);
        }
        else {
            pw1.setEchoChar('*');
        }
    }//GEN-LAST:event_Box2ActionPerformed

    private void Box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4ActionPerformed
        if(Box4.isSelected()){
            pw.setEchoChar((char)0);
        }
        else {
            pw.setEchoChar('*');
        }
    }//GEN-LAST:event_Box4ActionPerformed

    private void saveAdmin(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String bday = sdf.format(bd.getDate());
        
        try{
            pst = conn.prepareStatement("update registrar set regFn=?,regMn=?,regLn=?,regSf=?,regBdate=?,regAddress=?"
                    + ",regNumber=?,regEmail=?,regUn=?,regPw=? where regId = ?");
            pst.setString(1,fn.getText());
            pst.setString(2,mn.getText());
            pst.setString(3,ln.getText());
            pst.setString(4,sf.getText());
            pst.setString(5,bday);
            pst.setString(6,ad.getText());
            pst.setString(7,cn.getText());
            pst.setString(8,em.getText());
            pst.setString(9,un.getText());
            pst.setString(10,pw.getText());
            pst.setString(11,id.getText());
            
            if(JOptionPane.showConfirmDialog(null,"Confirm Update?","Account",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Account Updated.");
            }else{
                System.out.println("Attempt Failed.");
            }
            
        }catch(HeadlessException | SQLException e){
            System.out.println(e);
        }
    }
    private void saveEmp(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String bday = sdf.format(bd.getDate());
        try{
            pst = conn.prepareStatement("update employee set efirstName=?,emiddleName=?,elastName=?,eSuffix=?,ebirthDate=?,eAddress=?"
                    + ",eNumber=?,eEmail=?,eUsername=?,ePassword=? where employeeId = ?");
            pst.setString(1,fn.getText());
            pst.setString(2,mn.getText());
            pst.setString(3,ln.getText());
            pst.setString(4,sf.getText());
            pst.setString(5, bday);
            pst.setString(6,ad.getText());
            pst.setString(7,cn.getText());
            pst.setString(8,em.getText());
            pst.setString(9,un.getText());
            pst.setString(10,pw.getText());
            pst.setString(11,id.getText());
            
            if(JOptionPane.showConfirmDialog(null,"Confirm Update?","Account",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Account Updated.");
            }else{
                System.out.println("Attempt Failed.");
            }
            
        }catch(HeadlessException | SQLException e){
            System.out.println(e);
        }
    }
    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
           String pos = po.getText();
           if(pw.getText().equals(pw1.getText())){
               if(pos.equals("Registrar")){
               saveAdmin();ac();
                }else{
                    saveEmp();
                }
           }else{
               JOptionPane.showMessageDialog(null,"Password and Confirm Password does not match!");
           }
           
           
           
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Box2;
    private javax.swing.JCheckBox Box4;
    public javax.swing.JTextField ad;
    public com.toedter.calendar.JDateChooser bd;
    private javax.swing.JButton btn;
    public javax.swing.JTextField cn;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField ln;
    public javax.swing.JTextField mn;
    public javax.swing.JTextField po;
    private javax.swing.JPasswordField pw;
    private javax.swing.JPasswordField pw1;
    public javax.swing.JTextField sf;
    public javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
