/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yngMain;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class lists extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst,pst1;
    ResultSet rs,rs1;
    
    public ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));
    public String empId;
    
    static final String USERNAME = "root";
    static final String PASSWORD = "";
    static final String DATACONN = "jdbc:mysql://localhost/sql12655413";
    
    public lists() {
        initComponents();
        conn = (com.mysql.jdbc.Connection) con();
        setResizable(false);
        setTitle("Students List");
        setIconImage(logo.getImage()); 
        studentList();
        vital();
    }
    
    void vital(){
        tid.setVisible(false);
        try{
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer(); // create a renderer
        centerRenderer.setHorizontalAlignment(JLabel.CENTER); // set its alignment
        students.setDefaultRenderer(Object.class, centerRenderer);
        students.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS); // set the auto resize mode to all columns
        students.setFillsViewportHeight(true); // set the table to fill the viewport height
        }catch(Exception e){
            System.out.println(e);
        }

    }
    
    public final Connection con(){
        try{
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(DATACONN,USERNAME,PASSWORD);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return conn;
        
    }
    
   
    
    public void studentList(){
        try{
            pst = conn.prepareStatement("select * from grades "
                    + "inner join studentdata on studentdata.studentId = grades.studentId "
                    + "inner join employee on employee.employeeId = grades.employeeid "
                    + "inner join subjects on subjects.subjectId = grades.subjectId "
                    + "inner join schedule on schedule.scheduleId = grades.scheduleId "
                    + "where grades.employeeId = ? and grades.subjectId = ? order by studentdata.lastName asc");
            pst.setString(1,tid.getText());
            pst.setString(2,subjectsId.getText());
            
               // System.out.println(tid.getText()+" ~ "+subjectsId.getText());
            rs = pst.executeQuery();
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel) students.getModel();
            dtm.setRowCount(0);
            try{
            while (rs.next()){
                Vector v = new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("gradesId"));
                    v.add(rs.getString("studentdata.studentId"));
                    v.add(rs.getString("lastName") + ", " + rs.getString("firstName")+" "+rs.getString("middleName"));
                    v.add(rs.getString("subjects.description"));
                    v.add(rs.getString("prelim"));
                    v.add(rs.getString("midterm"));
                    v.add(rs.getString("finals"));
                    v.add(rs.getString("average"));
                    v.add(rs.getString("gwa"));
                    v.add(rs.getString("remarks"));
                    
                    System.out.println(rs.getString("lastName") + " added.");
                }
                dtm.addRow(v);
            }
            }catch(SQLException e){
                System.out.println(e);
            }
            
            
        }catch (SQLException ex) {
           System.out.println(ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        students = new javax.swing.JTable();
        note1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        studentunitsId = new javax.swing.JLabel();
        subjectsId = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        toGrades = new javax.swing.JButton();
        forSub = new javax.swing.JLabel();
        forStud = new javax.swing.JLabel();
        forEmp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        klass = new javax.swing.JLabel();
        ref = new javax.swing.JButton();
        n = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "ID", "Student Name", "Subject", "Prelim", "Midterm", "Finals", "Average", "GWA", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        students.setRowHeight(30);
        students.getTableHeader().setReorderingAllowed(false);
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(students);
        if (students.getColumnModel().getColumnCount() > 0) {
            students.getColumnModel().getColumn(0).setMinWidth(0);
            students.getColumnModel().getColumn(0).setPreferredWidth(0);
            students.getColumnModel().getColumn(0).setMaxWidth(0);
            students.getColumnModel().getColumn(1).setMinWidth(110);
            students.getColumnModel().getColumn(1).setPreferredWidth(110);
            students.getColumnModel().getColumn(1).setMaxWidth(110);
            students.getColumnModel().getColumn(3).setMinWidth(0);
            students.getColumnModel().getColumn(3).setPreferredWidth(0);
            students.getColumnModel().getColumn(3).setMaxWidth(0);
            students.getColumnModel().getColumn(4).setMinWidth(85);
            students.getColumnModel().getColumn(4).setPreferredWidth(85);
            students.getColumnModel().getColumn(4).setMaxWidth(85);
            students.getColumnModel().getColumn(5).setMinWidth(85);
            students.getColumnModel().getColumn(5).setPreferredWidth(85);
            students.getColumnModel().getColumn(5).setMaxWidth(85);
            students.getColumnModel().getColumn(6).setMinWidth(85);
            students.getColumnModel().getColumn(6).setPreferredWidth(85);
            students.getColumnModel().getColumn(6).setMaxWidth(85);
            students.getColumnModel().getColumn(7).setMinWidth(85);
            students.getColumnModel().getColumn(7).setPreferredWidth(85);
            students.getColumnModel().getColumn(7).setMaxWidth(85);
            students.getColumnModel().getColumn(8).setMinWidth(100);
            students.getColumnModel().getColumn(8).setPreferredWidth(100);
            students.getColumnModel().getColumn(8).setMaxWidth(100);
            students.getColumnModel().getColumn(9).setMinWidth(100);
            students.getColumnModel().getColumn(9).setPreferredWidth(100);
            students.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 840, 350);

        note1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        note1.setText("Students Grades List");
        note1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(note1);
        note1.setBounds(20, 10, 450, 30);

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(750, 10, 100, 30);
        getContentPane().add(studentunitsId);
        studentunitsId.setBounds(440, 470, 170, 30);
        getContentPane().add(subjectsId);
        subjectsId.setBounds(290, 470, 170, 30);
        getContentPane().add(tid);
        tid.setBounds(0, 0, 140, 30);

        toGrades.setText("Encode Grades");
        toGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGradesActionPerformed(evt);
            }
        });
        getContentPane().add(toGrades);
        toGrades.setBounds(700, 410, 150, 30);
        getContentPane().add(forSub);
        forSub.setBounds(80, 470, 90, 20);
        getContentPane().add(forStud);
        forStud.setBounds(20, 470, 90, 20);
        getContentPane().add(forEmp);
        forEmp.setBounds(180, 470, 90, 20);

        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Select student first before encoding grades");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(411, 416, 280, 20);
        getContentPane().add(klass);
        klass.setBounds(140, 470, 90, 20);

        ref.setText("Refresh");
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });
        getContentPane().add(ref);
        ref.setBounds(10, 410, 100, 30);

        n.setText("Search by Name");
        n.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nFocusLost(evt);
            }
        });
        getContentPane().add(n);
        n.setBounds(480, 10, 260, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = n.getText();
        String nn = "Search by Name";
        
        if(name.equals(nn)){
            JOptionPane.showMessageDialog(null,"Name is required to sort list.");studentList();
        }else{
            try{
                pst = conn.prepareStatement("select * from grades "
                    + "inner join studentdata on studentdata.studentId = grades.studentId "
                    + "inner join employee on employee.employeeId = grades.employeeid "
                    + "inner join subjects on subjects.subjectId = grades.subjectId "
                    + "inner join schedule on schedule.scheduleId = grades.scheduleId "
                    + "inner join course on course.courseId = studentdata.courseId "    
                    + "where grades.employeeId = ? and grades.subjectId = ? and (firstName like ? or lastName like ?) order by studentdata.lastName asc");
                pst.setString(1,tid.getText());
                pst.setString(2,subjectsId.getText());
                pst.setString(3,"%"+name+"%");
                pst.setString(4,"%"+name+"%");
            
                //System.out.println(tid.getText()+" ~ "+subjectsId.getText());
            rs = pst.executeQuery();
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel) students.getModel();
            dtm.setRowCount(0);
            try{
            while (rs.next()){
                Vector v = new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("gradesId"));
                    v.add(rs.getString("studentdata.studentId"));
                    v.add(rs.getString("lastName") + ", " + rs.getString("firstName")+" "+rs.getString("middleName"));
                    v.add(rs.getString("subjects.description"));
                    v.add(rs.getString("prelim"));
                    v.add(rs.getString("midterm"));
                    v.add(rs.getString("finals"));
                    v.add(rs.getString("average"));
                    v.add(rs.getString("gwa"));
                    v.add(rs.getString("remarks"));
                    System.out.println(rs.getString("lastName") + " added.");
                }
                dtm.addRow(v);
            }
            }catch(SQLException e){
                System.out.println(e);
            }
            
            
        }catch (SQLException ex) {
           System.out.println(ex);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    String schedId;
    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
            DefaultTableModel dtm = (DefaultTableModel)students.getModel();
            int si = students.getSelectedRow();
            forStud.setText(dtm.getValueAt(si, 1).toString());
            schedId = dtm.getValueAt(si,4).toString();
    }//GEN-LAST:event_studentsMouseClicked

    private void toGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGradesActionPerformed
        String fullname=null;
        String subject=null;
        try{
                pst = conn.prepareStatement("select * from studentdata where studentId = ?");
                pst.setString(1,forStud.getText());
                
                rs =pst.executeQuery();
                if(rs.next()){
                 fullname = rs.getString("lastName")+ ", "+rs.getString("firstName")+" "+rs.getString("middleName"); 
                }
                
                pst1 = conn.prepareStatement("select * from subjects where subjectId = ?");
                pst1.setString(1,subjectsId.getText());
                rs1 = pst1.executeQuery();
                
                if(rs1.next()){
                    subject = rs1.getString("subjectId");
                }
                
                grades togo = new grades();
                togo.studentId.setText(forStud.getText());
                System.out.println("FORSTUD FROM LISTS : "+forStud.getText());
                togo.studentName.setText(fullname);
                togo.subjectId.setText(subject);
                System.out.println("FORSUBJECT FROM LISTS : "+ subject);
                togo.subjectdesc.setText(forSub.getText());
                togo.EMPID.setText(forEmp.getText());
                togo.skedyul.setText(studentunitsId.getText());
                togo.klase.setText(klass.getText());
                togo.refresh();
                togo.setVisible(true);
                
            }catch(Exception e){
                System.out.println(e);
            }

  
        System.out.println("Full Name: "+fullname);
        System.out.println("subject Id: "+subject);
    }//GEN-LAST:event_toGradesActionPerformed

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
        // TODO add your handling code here:
        studentList();
    }//GEN-LAST:event_refActionPerformed

    private void nFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nFocusGained
        String nn = "Search by Name";
        String tt = n.getText();
        if(tt.equals(nn)){
            n.setText(null);
        }
    }//GEN-LAST:event_nFocusGained

    private void nFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nFocusLost
        String nn = "Search by Name";
        String tt = n.getText();
        if(n.equals("")){
            n.setText(nn);
        }else if(n == null){
            n.setText(nn);
        }else if(tt.isEmpty()){
            n.setText(nn);
        }
    }//GEN-LAST:event_nFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel forEmp;
    public javax.swing.JLabel forStud;
    public javax.swing.JLabel forSub;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel klass;
    private javax.swing.JTextField n;
    public javax.swing.JLabel note1;
    private javax.swing.JButton ref;
    private javax.swing.JTable students;
    public javax.swing.JLabel studentunitsId;
    public javax.swing.JLabel subjectsId;
    public javax.swing.JLabel tid;
    private javax.swing.JButton toGrades;
    // End of variables declaration//GEN-END:variables
}
