/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yngMain;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;

/**
 *
 * @author aa321
 */
public class login extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst,pst1,pst2,pst3;
    ResultSet rs,rs1,rs2,rs3;
    public ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));
    //static final String USERNAME = "sql12655413";
    //static final String PASSWORD = "K8Sk77cGK9";
    //static final String DATACONN = "jdbc:mysql://sql12.freesqldatabase.com:3306/sql12655413";
    
    static final String USERNAME = "root";
    static final String PASSWORD = "";
    static final String DATACONN = "jdbc:mysql://localhost/sql12655413";
    
    public login() {
        initComponents();
        conn = (com.mysql.jdbc.Connection) con();
        setResizable(false);
        setTitle("Log In");
        setIconImage(logo.getImage()); 
        randomPass();
    }
    

    public final Connection con(){
        try{
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(DATACONN,USERNAME,PASSWORD);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return conn;
        
    }
    
    String gen=null;
    public void randomPass(){
        String characters="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        String randomstr = "";
        int length=8;   
        Random rand = new Random();
        
        char[]text = new char[length];
        for(int i=0; i<length;i++){
        text[i] = characters.charAt(rand.nextInt(characters.length()));
        }
        for(int i =0; i<text.length;i++){
            randomstr += text[i];
            gen = randomstr;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logIn = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JButton();
        Box2 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rec = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        rc = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lock = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        em1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        rc1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 440));
        setSize(new java.awt.Dimension(420, 440));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        logIn.setBackground(new java.awt.Color(250, 250, 250));
        logIn.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YNG                  ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 380, 50);

        jLabel5.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("            Grading System");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 0, 380, 50);

        logIn.add(jPanel2);
        jPanel2.setBounds(-10, 0, 430, 50);

        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        logIn.add(un);
        un.setBounds(100, 120, 190, 30);

        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwKeyPressed(evt);
            }
        });
        logIn.add(pw);
        pw.setBounds(100, 180, 190, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Email:");
        logIn.add(jLabel2);
        jLabel2.setBounds(100, 90, 70, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password:");
        logIn.add(jLabel3);
        jLabel3.setBounds(100, 150, 110, 30);

        LOGIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LOGIN.setText("Login");
        LOGIN.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 1, true));
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        LOGIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LOGINKeyPressed(evt);
            }
        });
        logIn.add(LOGIN);
        LOGIN.setBounds(100, 270, 190, 30);

        Box2.setBackground(new java.awt.Color(250, 250, 250));
        Box2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Box2.setText("Show Password");
        Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2ActionPerformed(evt);
            }
        });
        logIn.add(Box2);
        Box2.setBounds(100, 210, 100, 30);
        logIn.add(jSeparator1);
        jSeparator1.setBounds(100, 250, 190, 3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Forgot Password?");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        logIn.add(jLabel4);
        jLabel4.setBounds(290, 365, 110, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Account Locked?");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        logIn.add(jLabel14);
        jLabel14.setBounds(290, 330, 110, 30);

        getContentPane().add(logIn, "card2");

        rec.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("RECOVER YOUR ACCOUNT");
        rec.add(jLabel6);
        jLabel6.setBounds(10, 0, 390, 50);
        rec.add(em);
        em.setBounds(25, 130, 180, 25);

        jLabel7.setText("Enter Email");
        rec.add(jLabel7);
        jLabel7.setBounds(25, 100, 180, 25);

        jButton1.setText("Send Recovery Code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        rec.add(jButton1);
        jButton1.setBounds(25, 170, 180, 25);
        rec.add(jSeparator2);
        jSeparator2.setBounds(25, 160, 180, 3);

        jLabel8.setText("Enter Recovery Code");
        rec.add(jLabel8);
        jLabel8.setBounds(200, 270, 180, 25);
        rec.add(rc);
        rc.setBounds(200, 290, 180, 25);
        rec.add(jSeparator3);
        jSeparator3.setBounds(200, 320, 180, 3);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        rec.add(jButton2);
        jButton2.setBounds(200, 330, 180, 25);
        rec.add(jSeparator4);
        jSeparator4.setBounds(0, 45, 220, 3);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Log In");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        rec.add(jLabel10);
        jLabel10.setBounds(290, 365, 110, 30);

        getContentPane().add(rec, "card3");

        lock.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("UNLOCK YOUR ACCOUNT");
        lock.add(jLabel9);
        jLabel9.setBounds(10, 0, 390, 50);
        lock.add(em1);
        em1.setBounds(25, 130, 180, 25);

        jLabel11.setText("Enter Email");
        lock.add(jLabel11);
        jLabel11.setBounds(25, 100, 180, 25);

        jButton3.setText("Send Unlock Code");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        lock.add(jButton3);
        jButton3.setBounds(25, 170, 180, 25);
        lock.add(jSeparator5);
        jSeparator5.setBounds(25, 160, 180, 3);

        jLabel12.setText("Enter Code to Unlock");
        lock.add(jLabel12);
        jLabel12.setBounds(200, 270, 180, 25);
        lock.add(rc1);
        rc1.setBounds(200, 290, 180, 25);
        lock.add(jSeparator6);
        jSeparator6.setBounds(200, 320, 180, 3);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        lock.add(jButton4);
        jButton4.setBounds(200, 330, 180, 25);
        lock.add(jSeparator7);
        jSeparator7.setBounds(0, 45, 220, 3);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Log In");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        lock.add(jLabel13);
        jLabel13.setBounds(290, 365, 110, 30);

        getContentPane().add(lock, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int attempt = 0;
    private void log(){
        try {
            pst = conn.prepareStatement("select * from employee inner join department on department.departmentId = employee.departmentId where eUsername=? and ePassword=?");
            pst.setString(1, un.getText());
            pst.setString(2,pw.getText());
            
            rs = pst.executeQuery();

            if (rs.next()) {
                    dispose();
                    opsys op = new opsys();
                    if(rs.getString("ePosition").equals("Instructor")){
                        op.ph.setVisible(false);
                    }else if(rs.getString("ePosition").equals("Program Head")){
                        op.ph.setVisible(true);
                    }
                    JOptionPane.showMessageDialog(null,"Welcome, " + rs.getString("ePosition") + " "+ rs.getString("efirstName"));
                    
                    op.dept.setText(rs.getString("department"));
                    op.id.setText(rs.getString("employeeId"));
                    op.table();
                    op.note.setText("Welcome "+rs.getString("efirstName")+ " "+ rs.getString("elastName")+ ".");
                    op.setVisible(true);
                    
                    System.out.println("FROM LOG IN OUTPUT - Department: "+rs.getString("department"));

            }else{
                pst1 = conn.prepareStatement("select * from registrar where regUn = ? and regPw = ? and position =?");
                pst1.setString(1,un.getText());
                pst1.setString(2,pw.getText());
                pst1.setString(3,"Registrar");
                
                rs1 = pst1.executeQuery();
                
                if(rs1.next()){
                    registrar r = new registrar();
                    r.wc.setText("Welcome, "+rs1.getString("position")+" "+rs1.getString("regFn"));
                    r.regId.setText(rs1.getString("regId"));
                    r.regname.setText(rs1.getString("regFn")+" "+rs1.getString("regLn"));
                    dispose();
                    JOptionPane.showMessageDialog(null,"Welcome Registrar "+rs1.getString("regFn")+"!","Registrar",JOptionPane.INFORMATION_MESSAGE);
                    
                    r.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null,"Username and password does not match.\nAttempt #"+attempt);
                }
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    String stat;
    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        isLock();
    }//GEN-LAST:event_LOGINActionPerformed
    
    private void isLock(){
        try{
            pst = conn.prepareStatement("select * from employee where eUsername = ?");
            pst.setString(1,un.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next()){
                stat = rs.getString("eStatus");
                if(stat.equals("Locked")){
                    JOptionPane.showMessageDialog(null,"Account was locked.");
                }else{
                    att();
                    log();
                }
                
            }else{
                log();
            }
            
        }catch(HeadlessException | SQLException e){
            
        }
    }
    
    private void att(){
        try {
            pst = conn.prepareStatement("select * from employee where eUsername = ?");
            pst.setString(1,un.getText());
            rs=pst.executeQuery();
            if(attempt>2){
                pst1 = conn.prepareStatement("update employee set eStatus = ? where eUsername =?");
                pst1.setString(1,"Locked");
                pst1.setString(2,un.getText());
                pst1.executeUpdate();
                attempt = 0;
                JOptionPane.showMessageDialog(null,"Account was locked.");
            }else
            if(rs.next()){
                String pass = rs.getString("ePassword");
                if(!pass.equals(pw.getText())){
                    attempt++;
                    System.out.println("Attempt number "+attempt +" for employee "+un.getText());
                }
            }
            
            
           
            
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        
    }
            
    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2ActionPerformed
        if(Box2.isSelected()){
            pw.setEchoChar((char)0);
        }
        else {
            pw.setEchoChar('*');
        }
    }//GEN-LAST:event_Box2ActionPerformed

    private void LOGINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LOGINKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           isLock();
        }
    }//GEN-LAST:event_LOGINKeyPressed

    private void pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            isLock();
        }
    }//GEN-LAST:event_pwKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        logIn.setVisible(false);
        lock.setVisible(false);
        rec.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        logIn.setVisible(true);
        rec.setVisible(false);
        lock.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            pst = conn.prepareStatement("update registrar set recovery =? where regEmail = ?");
            pst.setString(1,gen);
            pst.setString(2,em.getText());
            pst.executeUpdate();
            System.out.println("REGISTRAR");
        }catch(SQLException e){
            System.out.println(e);
        }
        try{
            pst = conn.prepareStatement("update employee set eRecovery = ? where eEmail = ?");
            pst.setString(1,gen);
            pst.setString(2,em.getText());
            pst.executeUpdate();
            System.out.println("EMPLOYEE");
        }catch(SQLException e){
            System.out.println(e);
        }
        
        
        String from,to,host,sub,content;
        from = "setsystem.v1@gmail.com";
        to = em.getText();
        host = "localhost";
        sub= "Recovery Code!";
        
        content = """
                  <html>
                  <head>
                  <style>
                      body {
                          font-family: Arial, sans-serif;
                          margin: 20px;
                            background-color:whitesmoke;
                            align-text:center;
                      }
                      h2 {
                          color: #008CBA;
                      }
                      p {
                          font-size: 16px;
                      }
                      strong {
                          font-weight: bold;
                      }
                  </style>
                  </head>
                  <body>
                  <h2>Aloha!</h2>
                  <p>We've found your Account!</p>
                  <p><strong>To recover your account, here is recovery code.</strong></p>
                  <p><strong>Email:</strong> """+em.getText()+"</p>\n" +
        "<p><strong>Recovery Code:</strong> "+gen+"</p>\n\n" +   
        "</body>\n" +
        "</html>";
        
                    Properties p = new Properties();
                    p.put("mail.smtp.auth","true");
                    p.put("mail.smtp.starttls.enable","true");
                    p.put("mail.smtp.host","smtp.gmail.com");
                    p.put("mail.smtp.port","587");
                    Session s = Session.getDefaultInstance(p,new javax.mail.Authenticator(){
                    protected PasswordAuthentication getPasswordAuthentication(){
                        return new PasswordAuthentication("setsystem.v1@gmail.com","tacwtpwmbrguopkh");
                    }    
                    }); 
                    try{
                        MimeMessage m = new MimeMessage(s);
                        m.setFrom(from);
                        m.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
                        m.setSubject(sub);
                        m.setContent(content, "text/html; charset=utf-8");
                        Transport.send(m);
                        JOptionPane.showMessageDialog(null,"Recovery Code successfully sent.","Email",JOptionPane.INFORMATION_MESSAGE);
                        randomPass();
                        
                    } catch(MessagingException e){
                        JOptionPane.showMessageDialog(null,"Mail didn't sent.\n"+e,"Mail Status",JOptionPane.INFORMATION_MESSAGE);
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
            pst = conn.prepareStatement("select * from registrar where regEmail = ? and recovery = ?");
            pst.setString(1,em.getText());
            pst.setString(2,rc.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                account acc =new account();
                acc.id.setText(rs.getString("regId"));
                acc.ac();
                JOptionPane.showMessageDialog(null,"Account Found!\nUpdate your password and re-Log In.");
                dispose();
                acc.setVisible(true);
            }else{
                System.out.println("Not REG");
            }
            System.out.println("REGISTRAR");
        }catch(SQLException e){
            System.out.println(e);
        }
        try{
            pst = conn.prepareStatement("select * from employee where eRecovery = ? and eEmail = ?");
            pst.setString(1,rc.getText());
            pst.setString(2,em.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                account acc =new account();
                acc.id.setText(rs.getString("employeeId"));
                acc.ca();
                JOptionPane.showMessageDialog(null,"Account Found!\nUpdate your password and re-Log In.");
                dispose();
                acc.setVisible(true);
            }else{
            }
            
            System.out.println("EMPLOYEE");
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            pst = conn.prepareStatement("update registrar set recovery =? where regEmail = ?");
            pst.setString(1,gen);
            pst.setString(2,em1.getText());
            pst.executeUpdate();
        }catch(SQLException e){
            System.out.println(e);
        }
        try{
            pst = conn.prepareStatement("update employee set eRecovery = ? where eEmail = ?");
            pst.setString(1,gen);
            pst.setString(2,em1.getText());
            pst.executeUpdate();
        }catch(SQLException e){
            System.out.println(e);
        }
        
        
        String from,to,host,sub,content;
        from = "setsystem.v1@gmail.com";
        to = em1.getText();
        host = "localhost";
        sub= "Unlock Code!";
        
        content = """
                  <html>
                  <head>
                  <style>
                      body {
                          font-family: Arial, sans-serif;
                          margin: 20px;
                          background-color:whitesmoke;
                          align-text:center;
                      }
                      h2 {
                          color: #008CBA;
                      }
                      p {
                          font-size: 16px;
                          
                      }
                      strong {
                          font-weight: bold;
                      }
                  </style>
                  </head>
                  <body>
                  <h2>Aloha!</h2>
                  <p>We've found your Account!</p>
                  <p><strong>To unlock your account, here is unlock code.</strong></p>
                  <p><strong>Email:</strong> """+em1.getText()+"</p>\n" +
        "<p><strong>Unlock Code:</strong> "+gen+"</p>\n\n" +   
        "</body>\n" +
        "</html>";
        
                    Properties p = new Properties();
                    p.put("mail.smtp.auth","true");
                    p.put("mail.smtp.starttls.enable","true");
                    p.put("mail.smtp.host","smtp.gmail.com");
                    p.put("mail.smtp.port","587");
                    Session s = Session.getDefaultInstance(p,new javax.mail.Authenticator(){
                    protected PasswordAuthentication getPasswordAuthentication(){
                        return new PasswordAuthentication("setsystem.v1@gmail.com","tacwtpwmbrguopkh");
                    }    
                    }); 
                    try{
                        MimeMessage m = new MimeMessage(s);
                        m.setFrom(from);
                        m.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
                        m.setSubject(sub);
                        m.setContent(content, "text/html; charset=utf-8");
                        Transport.send(m);
                        JOptionPane.showMessageDialog(null,"Unlock Code successfully sent.","Email",JOptionPane.INFORMATION_MESSAGE);
                        randomPass();
                        
                    } catch(MessagingException e){
                        JOptionPane.showMessageDialog(null,"Mail didn't sent.\n"+e,"Mail Status",JOptionPane.INFORMATION_MESSAGE);
                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            pst =conn.prepareStatement("select * from registrar where regUn = ? and recovery =?");
            pst.setString(1, em1.getText());
            pst.setString(2,rc1.getText());
            pst1=conn.prepareStatement("select * from employee where eEmail = ? and eRecovery =?");
            pst1.setString(1, em1.getText());
            pst1.setString(2,rc1.getText());
            
            rs = pst.executeQuery();
            rs1=pst1.executeQuery();
            
            if(rs.next()){
                //update registrar
                pst2 = conn.prepareStatement("update registrar set status = ? where regUn = ?");
                pst2.setString(1,"Active");
                pst2.setString(2,em1.getText());
                pst2.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registrar Account Updated.");
            }else{System.out.println("not registrar");}
            if(rs1.next()){
                //update employee
                pst3 = conn.prepareStatement("update employee set eStatus = ? where eEmail = ?");
                pst3.setString(1,"Active");
                pst3.setString(2,em1.getText());
                pst3.executeUpdate();
                JOptionPane.showMessageDialog(null,"Employee Account Updated.");
            }else{System.out.println("not employee");}
            
        }catch(HeadlessException | SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        logIn.setVisible(true);
        rec.setVisible(false);
        lock.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        logIn.setVisible(false);
        rec.setVisible(false);
        lock.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(JOptionPane.showConfirmDialog(null,"Confirm Exit?","Exit",0)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Box2;
    private javax.swing.JButton LOGIN;
    private javax.swing.JTextField em;
    private javax.swing.JTextField em1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel lock;
    private javax.swing.JPanel logIn;
    private javax.swing.JPasswordField pw;
    private javax.swing.JTextField rc;
    private javax.swing.JTextField rc1;
    private javax.swing.JPanel rec;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables

}
