/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yngMain;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aa321
 */
public class opsys extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    int q,i,d;
    public ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));
    
    public String empId;
    
    static final String USERNAME = "root";
    static final String PASSWORD = "";
    static final String DATACONN = "jdbc:mysql://localhost/sql12655413";
    
    public opsys() {
        initComponents();
        conn = (com.mysql.jdbc.Connection) con();
        setResizable(false);
        setTitle("Home");
        setIconImage(logo.getImage()); 
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer(); // create a renderer
        centerRenderer.setHorizontalAlignment(JLabel.CENTER); // set its alignment
        subjects.setDefaultRenderer(Object.class, centerRenderer);
        
        forCourse();
        HIDE();
    }
    
    private void HIDE(){
        suid.setVisible(false);
        subid.setVisible(false);
    }
    
    public final Connection con(){
        try{
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(DATACONN,USERNAME,PASSWORD);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return conn;
        
    }
    
    public void table(){
        try{
            pst = conn.prepareStatement("select * from schedule inner join course on course.courseId = schedule.courseId inner join subjects on subjects.subjectId = schedule.subjectId inner join employee on employee.employeeId = schedule.employeeId where schedule.employeeId = ?");
            pst.setString(1,id.getText());
            rs = pst.executeQuery();
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel) subjects.getModel();
            dtm.setRowCount(0);
            while (rs.next()){
                Vector v = new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("scheduleId"));
                    v.add(rs.getString("description"));
                    v.add(rs.getString("course"));
                    v.add(rs.getString("schedule.year"));
                    v.add(rs.getString("subjectId"));
                  
                }
                dtm.addRow(v);
            }
            
            
        }catch (SQLException ex) {
           System.out.println(ex);
        }
    }

    public void forCourse(){
        course.removeAllItems();
        try{
            pst = conn.prepareStatement("select * from course order by degree asc");
            rs=pst.executeQuery();
            course.addItem("Select Course");
            while(rs.next()){
                course.addItem(rs.getString("course"));
            }
             
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lo = new javax.swing.JButton();
        xac = new javax.swing.JButton();
        note = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjects = new javax.swing.JTable();
        year = new javax.swing.JComboBox<>();
        Sort = new javax.swing.JButton();
        course = new javax.swing.JComboBox<>();
        sl = new javax.swing.JButton();
        sg = new javax.swing.JButton();
        note2 = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        ph = new javax.swing.JButton();
        dept = new javax.swing.JLabel();
        suid = new javax.swing.JLabel();
        subid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 730));
        setSize(new java.awt.Dimension(900, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("YNG Online Grading System");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 0, 800, 50);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ls.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 0, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 0, 890, 50);

        lo.setText("Log Out");
        lo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loActionPerformed(evt);
            }
        });
        jPanel1.add(lo);
        lo.setBounds(785, 64, 90, 23);

        xac.setText("Account");
        xac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacActionPerformed(evt);
            }
        });
        jPanel1.add(xac);
        xac.setBounds(655, 64, 120, 23);

        note.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        note.setText("Welcome Aboard to \"Position\" Tab.");
        note.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(note);
        note.setBounds(20, 60, 860, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel3.setLayout(null);

        subjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Subject", "Course", "Year Level", "subid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjects.setRowHeight(30);
        subjects.getTableHeader().setReorderingAllowed(false);
        subjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjects);
        if (subjects.getColumnModel().getColumnCount() > 0) {
            subjects.getColumnModel().getColumn(0).setMinWidth(0);
            subjects.getColumnModel().getColumn(0).setPreferredWidth(0);
            subjects.getColumnModel().getColumn(0).setMaxWidth(0);
            subjects.getColumnModel().getColumn(2).setPreferredWidth(80);
            subjects.getColumnModel().getColumn(3).setMinWidth(150);
            subjects.getColumnModel().getColumn(3).setPreferredWidth(150);
            subjects.getColumnModel().getColumn(3).setMaxWidth(150);
            subjects.getColumnModel().getColumn(4).setMinWidth(0);
            subjects.getColumnModel().getColumn(4).setPreferredWidth(0);
            subjects.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 840, 350);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "1", "2", "3", "4", "" }));
        jPanel3.add(year);
        year.setBounds(660, 14, 100, 22);

        Sort.setText("Sort");
        Sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortActionPerformed(evt);
            }
        });
        jPanel3.add(Sort);
        Sort.setBounds(770, 14, 72, 23);

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(course);
        course.setBounds(490, 14, 160, 22);

        sl.setText("View Student Lists");
        sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slActionPerformed(evt);
            }
        });
        jPanel3.add(sl);
        sl.setBounds(685, 420, 160, 23);

        sg.setText("View Student Grades");
        sg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgActionPerformed(evt);
            }
        });
        jPanel3.add(sg);
        sg.setBounds(10, 420, 160, 23);

        note2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        note2.setForeground(java.awt.Color.gray);
        note2.setText("(*Select subject first before view student lists or grades)");
        jPanel3.add(note2);
        note2.setBounds(110, 10, 340, 30);

        note1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        note1.setText("Subjects List ");
        note1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(note1);
        note1.setBounds(20, 10, 830, 30);

        id.setText("jLabel2");
        jPanel3.add(id);
        id.setBounds(0, 0, 0, 0);

        ph.setText("View Grades (For Approval)");
        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        jPanel3.add(ph);
        ph.setBounds(180, 420, 210, 23);

        dept.setText("jLabel2");
        jPanel3.add(dept);
        dept.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 100, 860, 470);
        jPanel1.add(suid);
        suid.setBounds(20, 580, 170, 30);
        jPanel1.add(subid);
        subid.setBounds(380, 580, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String subjectCode,subjectDesc;
    private void sgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgActionPerformed
         
        try{
            lists xvr = new lists();
            xvr.studentunitsId.setText(suid.getText());
            xvr.subjectsId.setText(subid.getText());
            xvr.tid.setText(id.getText());
            xvr.forSub.setText(subjectDesc);
            xvr.forEmp.setText(id.getText());
            xvr.studentList();
            xvr.note1.setText("Students Grades List: "+subjectDesc);
            xvr.klass.setText(dept.getText());
            xvr.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_sgActionPerformed
    
    
    private void subjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsMouseClicked
            DefaultTableModel dtm = (DefaultTableModel)subjects.getModel();
            int si = subjects.getSelectedRow();
            String c = dtm.getValueAt(si, 0).toString();
            suid.setText(c);
            
            try{
                pst = conn.prepareStatement("select * from subjects where subjectId = ?");
                pst.setString(1,dtm.getValueAt(si,4).toString());
                
                rs = pst.executeQuery();
                
                if(rs.next()){
                    subid.setText(rs.getString("subjectId"));
                    subjectCode = rs.getString("code");
                    subjectDesc = rs.getString("description");
                }
            }catch(SQLException e){
                System.out.println(e);
            }
    }//GEN-LAST:event_subjectsMouseClicked

    private void slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slActionPerformed
        students to = new students();
        to.studentunitsId.setText(suid.getText());
        to.subjectsId.setText(subid.getText());
        to.tid.setText(id.getText());
        to.forSub.setText(subjectDesc);
        to.forEmp.setText(id.getText());
        to.studentList();
        to.note1.setText("Students List: "+subjectDesc);
        to.klass.setText(dept.getText());
        to.setVisible(true);
        
    }//GEN-LAST:event_slActionPerformed

    private void loActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Confirm Log Out?","Log Out",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
            new login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_loActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        approve ve = new approve();
        
        ve.headId.setText(id.getText());
        ve.courshey.setText(dept.getText());
        ve.approval();
        ve.subject();
        ve.setVisible(true);
        
       System.out.println(id.getText());
    }//GEN-LAST:event_phActionPerformed

    private void SortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortActionPerformed
        String c = course.getSelectedItem().toString();
        String y = year.getSelectedItem().toString();
        String cn = "Select Course";
        String yn = "Select Year";
        
        if(c.equals(cn) && y.equals(yn)){
            table();
        }
        else if(c.equals(cn)){
            //bawal pa
            table();
            JOptionPane.showMessageDialog(null,"Select Course.");
        }else if(y.equals(yn)){
            //bawal pa din
            table();
            JOptionPane.showMessageDialog(null,"Select Year");
        }else{
            //go sort mo
            try{
            pst = conn.prepareStatement("select * from schedule inner join course on "
                    + "course.courseId = schedule.courseId inner join subjects on "
                    + "subjects.subjectId = schedule.subjectId inner join employee on "
                    + "employee.employeeId = schedule.employeeId where schedule.employeeId = ? and course = ? and schedule.year = ?");
            pst.setString(1,id.getText());
            pst.setString(2,course.getSelectedItem().toString());
            pst.setString(3,year.getSelectedItem().toString());
            rs = pst.executeQuery();
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int n = rsmd.getColumnCount();
            DefaultTableModel dtm=(DefaultTableModel) subjects.getModel();
            dtm.setRowCount(0);
            while (rs.next()){
                Vector v = new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("scheduleId"));
                    v.add(rs.getString("description"));
                    v.add(rs.getString("course"));
                    v.add(rs.getString("schedule.year"));
                    v.add(rs.getString("subjectId"));
                  
                }
                dtm.addRow(v);
            }
            
            
        }catch (SQLException ex) {
           System.out.println(ex);
        }
        }
        
    }//GEN-LAST:event_SortActionPerformed

    private void xacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacActionPerformed
        account acc = new account();
        acc.id.setText(id.getText());
        acc.setVisible(true);
        acc.ca();
    }//GEN-LAST:event_xacActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Confirm Exit?","Exit",0)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opsys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opsys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opsys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opsys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opsys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sort;
    private javax.swing.JComboBox<String> course;
    public javax.swing.JLabel dept;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lo;
    public javax.swing.JLabel note;
    public javax.swing.JLabel note1;
    public javax.swing.JLabel note2;
    public javax.swing.JButton ph;
    private javax.swing.JButton sg;
    private javax.swing.JButton sl;
    public javax.swing.JLabel subid;
    private javax.swing.JTable subjects;
    public javax.swing.JLabel suid;
    private javax.swing.JButton xac;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
